name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    runs-on: ubuntu-20.04
    container: debian:9 # glibc 2.24
    steps:
      - name: Deps
        run: apt update && apt install -y curl gcc

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          target: x86_64-unknown-linux-gnu
          profile: minimal
          components: clippy

      - name: Lint
        run: cargo clippy

      - name: Testing
        run: cargo test

      - name: Documentation
        run: cargo doc
