name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    runs-on: ubuntu-20.04
    container: debian:9 # glibc 2.24
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          profile: minimal

      - name: Unit tests
        run: cargo test --verbose

      - name: Build
        run: cargo build --verbose --release

      - name: Rename
        run: mv ./target/release/deadlinkrs ./target/release/deadlinkrs-linux

      - uses: actions/upload-artifact@v3
        with:
          name: deadlinkrs-linux
          path: ./target/release/deadlinkrs-linux
          if-no-files-found: 'error'

  release:
    runs-on: ubuntu-latest
    needs: [ linux ]
    env:
      GH_REPO: ${{ github.repository }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Getting version tag
        run: "echo \"RELEASE_TAG=${GITHUB_REF#refs/tags/}\" >> $GITHUB_ENV"

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: deadlinkrs-linux

      - name: Publish release
        run: >
          gh release create $RELEASE_TAG
            --title "$RELEASE_TAG"
            deadlinkrs-linux
